### ISSUE TITLE
Plan of v0.1.5

### ISSUE THREAD

**Issue by zhaouv** [zhaouv/vscode-markdown-draw#5]
+ fold svg #2 
+ save/load file #3
+ shortcut bind of webview (from some other forks of this repo)
+ other adjustion of webview #4

**Comment by hall** [comment]
So . . . I decided to make this my weekend project and went a little crazy with the commits; not only because I'm excited at the possibility of combining my favorite [hand-written notes app](https://xournalpp.github.io/) with my favorite [text-based notes app](https://www.dendron.so) but also because I've been looking for an excuse to learn some of the tools in this area a little better.

Anyway, I'm sure I probably made some bad changes but hopefully you'll find some good ones in there as well: https://gitlab.com/hall/draw

I published it to the marketplace so it might be easier to test (and I tried to put all of the interesting changes in the changelog). When you have time, take a look and let me know what you think.

**Comment by zhaouv** [comment]
Combining other draw-app instead of [syfxlin/graffiti-board](https://github.com/syfxlin/graffiti-board/tree/5945b126c945073eced5e6eb78658bc2a7375881) may be not so difficult. Actually the current board does not apply any smoothing. I just had not found other draw-app which is both easy to learn and good enough, at that time.
I uninstall my old extension and install the new extension(and restart VSC), seems something wrong...
<img width="919" alt="image" src="https://user-images.githubusercontent.com/26158289/169812325-daf7fd60-3196-422e-a751-b58ad5918981.png">

**Comment by zhaouv** [comment]
And anyway we can still `git remote add zhaouv https://github.com/zhaouv/vscode-markdown-draw.git` and `git remote add hall https://gitlab.com/hall/draw.git` to merge other's branch, even in different platform. I will read your code then I'm not busy.

**Comment by hall** [comment]
Yeah, I haven't done much searching (or even really dug into graffiti board's interface) but [signature pad](https://github.com/szimek/signature_pad) is probably the closest thing I could find (on the surface of it, at least).

Hm, any errors in the dev console? I'm guessing it doesn't like [some of the hardcoded linux-style path fragments](https://github.com/szimek/signature_pad/tree/f9f6af2804c65a8a6f16e5036b9a328e1dbcb7ed).

**Comment by hall** [comment]
Pushed a new version which _should_ (haven't figured out cross-platform testing on this yet; I'll try spinning up a VM later today) work on Windows: https://gitlab.com/hall/draw/-/commit/24458142a4c664dbd730915961288912a5395f3d.

Anyway, feel free to open an issue in that repo if you don't want to clutter this one :smile:

**Comment by zhaouv** [comment]
About signature pad, the line tool in graffiti-board is very useful. It's a trade off. easy to learn for developer/easy to use for user/powerful/weightless .etc. 
The change of paths do not solve the bug. And nothing in the `Ctrl+Shit+I` tool. Seems should debug the repo to see what happens. I will remain a issue or mr there latter.

**Comment by hall** [comment]
Ah, good point. I do like the shapes tools and hadn't considered that any alternative should provide similar functionality :+1: 

Anyway, I was able to test the extension on a Windows VM; I pushed a new version which is, at least somewhat, working (still with bugs, e.g., it doesn't seem to like the cursor being in the first 2-4 lines of the editor :shrug:,  but functional at least!).

**Comment by zhaouv** [comment]
done, will be closed in two weeks if no bug reported
